version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: petsdb
      POSTGRES_USER: petsuser
      POSTGRES_PASSWORD: petspassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
